### PR TITLE
Add basic tests

### PR DESCRIPTION
**Pull request by alexanderGugel**
Resubmitting #588 to merge into `next`.

Before merging this in, the following PRs are required (otherwise the tests would fail):

Accumulator fix: #570
Matrix fix: #536
DesktopEmulationMode rewrite (no longer breaking): #555
Quaternion fix: #590
MultipleTransition fix: #594

Still a WIP, but already better than no tests at all.

### CODE REVIEW

**Comment by michaelobriena** [comment]
@alexanderGugel can you look into the travis error?

**Comment by TheAlphaNerd** [comment]
looks to me like testling is attempting to launch firefox with testling rather than phantomjs

**Comment by alexanderGugel** [comment]
Hmmmm. Strange. According to http://docs.travis-ci.com/user/gui-and-headless-browsers/, PhantomJS should be pre-installed.

**Comment by TheAlphaNerd** [comment]
I think it has to do with the default testling is using… not sure why=

**Comment by TheAlphaNerd** [comment]
@alexanderGugel can you rebase against next please

**Comment by alexanderGugel** [comment]
Ok, Travis build succeeds now.
Travis uses Firefox 17.0 by default. I had to update to 35.0 since there seems to be some bugs in older versions of Firefox concerning dispatching custom events and having false-positives for infinite recursion.

**Comment by MylesBorins** [comment]
OMG OMG OMG OMG

LANDED!!!!!
:tada: :balloon:  :tada: :balloon:  :tada: :balloon:  :tada: :balloon:  :tada: :balloon: 
:fireworks:  :fireworks:   :fireworks:   :fireworks:   :fireworks: 
:tada: :balloon:  :tada: :balloon:  :tada: :balloon:  :tada: :balloon:  :tada: :balloon:  :tada: :balloon:  :tada: :balloon: 
d3e85881bd22bb9ef55af388c725b514c9e9b2b7
:tada: :balloon:  :tada: :balloon:  :tada: :balloon:  :tada: :balloon:  :tada: :balloon:  :tada: :balloon:  :tada: :balloon: 
:fireworks:  :fireworks:   :fireworks:   :fireworks:   :fireworks: 
:tada: :balloon:  :tada: :balloon:  :tada: :balloon:  :tada: :balloon:  :tada: :balloon:  :tada: :balloon:

**Pull request closed without merging**
