### PR TITLE
Add SizeAwareView class and example

### PR DESCRIPTION
**Pull request by arkadyp**
- Add SizeAwareView class
- Add example of SizeAwareView where a Surface's content changed on window resize

### CODE REVIEW

**Comment by michaelobriena** [comment]
Some linting issues but if you fix those this seems fine to me.  The only question should be should we just replace ContextualView with this.

**Comment by arkadyp** [comment]
Fixed the linting issues, my bad for forgetting to run 'npm run test' before submitting the pull request.

I think that replacing ContextualView would be a good idea.

**Comment by matthewtoast** [comment]
:+1:

**Comment by arkadyp** [comment]
I just updated this pull request to update the documentation inside of ContextualView to mark it as deprecated.

@michaelobriena @TheAlphaNerd In putting together this pull request, I noticed that some of our Views do not have the proper MPL license comment (e.g., Scroller.js, Lightbox.js) and it seems like all of the comments need to be updated so that they reflect the new year as they now all say "@copyright Famous Industries, Inc. 2014".

**Comment by TheAlphaNerd** [comment]
@arkadyp looks to me like you volunteered to update the dates :P

**Comment by alexanderGugel** [comment]
Done #582

**Comment by arkadyp** [comment]
Thanks @alexanderGugel

**Comment by TheAlphaNerd** [comment]
landed as 03dd313

**Pull request closed without merging**
