### PR TITLE
Fix options for docs

### PR DESCRIPTION
**Pull request by TheAlphaNerd**
We need to not have the square braces around options or the doc builder explodes

### CODE REVIEW

**Comment by StephanBijzitter** [comment]
I feel like this is not a fix but a workaround, though. The square braces are used to indicate the parameter is optional =-/

**Comment by TheAlphaNerd** [comment]
is that documented in the official jsdoc / yuidoc guide?

We are evaluating replacing our doc-generator with something closer to vanilla jsdoc.

**Comment by StephanBijzitter** [comment]
With yuidoc it is, don't know about jsdoc http://yui.github.io/yuidoc/syntax/ (search for `*param`)

**Comment by TheAlphaNerd** [comment]
ahh... good call.  Must be some jank in our end.  This should not be merged then. Thanks for the keen eye @StephanBijzitter

**Pull request closed without merging**
