### PR TITLE
small fix to Curve constraint calculation

### PR DESCRIPTION
**Pull request by desm**
Not sure about this fix, but it definitely works a lot better for me this way.  Thanks for considering!

### CODE REVIEW

**Comment by michaelobriena** [comment]
@browles can you take a look at this?

**Comment by browles** [comment]
@michaelobriena yep looks good. I'm surprised it was working at all.

**Comment by michaelobriena** [comment]
@browles Thanks.

**Comment by TheAlphaNerd** [comment]
landed as 7dc17c8

**Pull request closed without merging**
