### PR TITLE
Fix for setContent not doing anything because the surface was recalled from the DOM the next render cycle.

### PR DESCRIPTION
**Pull request by IjzerenHein**

### CODE REVIEW

**Comment by michaelobriena** [comment]
Can you elaborate on this?  Not sure the exact breaking condition.

**Comment by jd-carroll** [comment]
I'm with @michaelobriena, please see my comment: https://github.com/Famous/famous/issues/673#issuecomment-89352486

**Comment by IjzerenHein** [comment]
I'll provide you with a test case which shows the problem in action.

**Comment by IjzerenHein** [comment]
Hi, I've created a demo for this, which demonstrates the problem:
http://gloey.nl/apps/setContent/

To reproduce, press the "Trigger bug: Set Content, Hide and show after 2 secs" button.
This button executes two actions at once:
- setContent(copy value from right-top input to the content surface)
- hide (a SequentialLayout is used to remove the surface from the render-tree the next render cycle: `sequenceFrom([])`.

After 2 seconds, the surface is re-shown, and you would expect that the content that was set using 'setContent' be shown in the surface. But that is not the case and instead the content is shown that was last in the DOM.

Interesting note:
I tried reproducing this problem first with a RenderController, but was unable to. After some investigation I noticed that the RenderController still shows the content for at least 1 render-cycle after `.hide({duration: 0})` was executed on the render-controller and thus causes this bug not to be triggered.

**Comment by michaelobriena** [comment]
Thanks for the test case.  This makes sense.  @TheAlphaNerd This is mergable.

**Comment by MylesBorins** [comment]
@michaelobriena which milestone?

**Comment by jd-carroll** [comment]
Are we certain that the surface will be recalled successfully after
preventing the initial recall?

**Comment by MylesBorins** [comment]
@michaelobriena can you close this?

**Pull request closed without merging**
