### PR TITLE
Transitionable delay fix

### PR DESCRIPTION
**Pull request by xiamike**

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
ruhroh trailing spaces

**Comment by michaelobriena** [comment]
line 174.

**Comment by timjchin** [comment]
To add some context about this solution. If you have a Transitionable, and you call: 

```js
var trans = new Transitionable(1)
trans.set(0, { duration: 500 });
trans.delay(500);
trans.set(1, { duration: 500 });
```

You would expect that the Transitionable starts at one, animates to 0, waits 500 ms and animates to 1. The current `delay` does not take into account future actions, so the Transitionable would animate to 0, is instantly set to 1 (because the .get() returned is the state when delay was called), waits 500 ms, and animates to 1 -- which does nothing, since it is already at 1.

This pull request changes delay to take into account the pending action queue.

**Comment by michaelobriena** [comment]
Good change

**Comment by TheAlphaNerd** [comment]
landed as 26a173d

**Pull request closed without merging**
